language: python

python:
  - '2.7'
  - '3.6'

install:
  - pip install .
  - pip install pytest-cov coveralls pycodestyle
  - pip install flask pygments
  - bin/build_js_bundle.sh complete
  - pip list
  - pip show orca

script:
  - pycodestyle orca
  - py.test --cov orca --cov-report term-missing

after_success:
  - coveralls
  - bin/build_docs.sh

env:
  global:
    secure: DMQgAnged8quDKf3pTLG6RZVMKhrhZfYSRKaPFJrERXEOuRPJjC4QYG24pdyCV2aOQbSOiF16vSctpDmMfjLDARkhNm8FvYYCOKLkE+4ijQ4vE/uQaHsnosGS/1LOOFGjK0h2dvm4CNJqV1JUhCKeOVe/87GGY2JVBy+NJnsl70=
